"""add llm_calls table and users.is_admin

Revision ID: a196ff110db0
Revises: 7ea50f6d2406
Create Date: 2026-09-10 20:50:34.569709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a196ff110db0'
down_revision: Union[str, None] = '7ea50f6d2406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=150), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_course_id'), 'llm_calls', ['course_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_created_at'), 'llm_calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_calls_endpoint'), 'llm_calls', ['endpoint'], unique=False)
    op.create_index(op.f('ix_llm_calls_module_id'), 'llm_calls', ['module_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_purpose'), 'llm_calls', ['purpose'], unique=False)
    op.create_index(op.f('ix_llm_calls_request_id'), 'llm_calls', ['request_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_user_id'), 'llm_calls', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_llm_calls_user_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_request_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_purpose'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_module_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_endpoint'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_created_at'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_course_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    # ### end Alembic commands ###
