"""add course difficulty and module summary

Revision ID: ce4a63784746
Revises: ea3660b771c5
Create Date: 2026-09-09 11:27:49.004630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4a63784746'
down_revision: Union[str, None] = 'ea3660b771c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'courses',
        sa.Column('current_difficulty', sa.String(length=50), nullable=False, server_default='intermediate'),
    )
    op.add_column('modules', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'summary')
    op.drop_column('courses', 'current_difficulty')
    # ### end Alembic commands ###
